<?php
require 'config.php'; auth();
if($_SERVER['REQUEST_METHOD']==='POST'){$a=$_POST['action']??'';
if($a==='create')db()->prepare("INSERT INTO teachers(first_name,last_name,phone,email,subjects,salary_type,salary_amount)VALUES(?,?,?,?,?,?,?)")->execute([$_POST['first_name'],$_POST['last_name'],$_POST['phone'],$_POST['email'],$_POST['subjects'],$_POST['salary_type'],$_POST['salary_amount']]);
elseif($a==='update')db()->prepare("UPDATE teachers SET first_name=?,last_name=?,phone=?,email=?,subjects=?,salary_type=?,salary_amount=?,status=? WHERE id=?")->execute([$_POST['first_name'],$_POST['last_name'],$_POST['phone'],$_POST['email'],$_POST['subjects'],$_POST['salary_type'],$_POST['salary_amount'],$_POST['status'],$_POST['id']]);
elseif($a==='delete')db()->prepare("DELETE FROM teachers WHERE id=?")->execute([$_POST['id']]);
header('Location: teachers.php');exit;}
$teachers=db()->query("SELECT * FROM teachers ORDER BY created_at DESC")->fetchAll();
?>
<!DOCTYPE html><html><head><title>Teachers</title><script src="https://cdn.tailwindcss.com"></script><script defer src="https://cdn.jsdelivr.net/npm/alpinejs@3.x.x/dist/cdn.min.js"></script></head>
<body class="bg-gray-100" x-data="{modal:false,form:{},edit:false}"><div class="flex"><nav class="bg-gray-800 text-white w-64 min-h-screen p-4"><h2 class="text-xl font-bold mb-6">Learning CRM</h2><a href="dashboard.php" class="block py-2 px-4 hover:bg-gray-700 rounded mb-2">📊 Dashboard</a><a href="students.php" class="block py-2 px-4 hover:bg-gray-700 rounded mb-2">👥 Students</a><a href="teachers.php" class="block py-2 px-4 bg-gray-700 rounded mb-2">👨‍🏫 Teachers</a><a href="groups.php" class="block py-2 px-4 hover:bg-gray-700 rounded mb-2">📚 Groups</a><a href="payments.php" class="block py-2 px-4 hover:bg-gray-700 rounded mb-2">💰 Payments</a><a href="expenses.php" class="block py-2 px-4 hover:bg-gray-700 rounded mb-2">📉 Expenses</a><a href="logout.php" class="block py-2 px-4 hover:bg-red-700 rounded mt-4">🚪 Logout</a></nav>
<main class="flex-1 p-8"><div class="flex justify-between items-center mb-8"><h1 class="text-3xl font-bold">Teachers</h1><button @click="modal=true;form={};edit=false" class="bg-blue-600 text-white px-4 py-2 rounded">+ Add Teacher</button></div>
<div class="bg-white rounded-lg shadow overflow-hidden"><table class="w-full"><thead class="bg-gray-50"><tr><th class="px-6 py-3 text-left">Name</th><th class="px-6 py-3 text-left">Phone</th><th class="px-6 py-3 text-left">Subjects</th><th class="px-6 py-3 text-left">Salary</th><th class="px-6 py-3 text-left">Actions</th></tr></thead><tbody class="divide-y">
<?php foreach($teachers as $t): ?><tr><td class="px-6 py-4"><?=htmlspecialchars($t['first_name'].' '.$t['last_name'])?></td><td class="px-6 py-4"><?=$t['phone']??'-'?></td><td class="px-6 py-4"><?=$t['subjects']??'-'?></td><td class="px-6 py-4">$<?=number_format($t['salary_amount']??0,2)?></td><td class="px-6 py-4"><button @click="form=<?=htmlspecialchars(json_encode($t))?>;modal=true;edit=true" class="text-blue-600 mr-3">Edit</button><form method="POST" class="inline" onsubmit="return confirm('Delete?')"><input type="hidden" name="action" value="delete"><input type="hidden" name="id" value="<?=$t['id']?>"><button class="text-red-600">Delete</button></form></td></tr><?php endforeach; ?>
</tbody></table></div>
<div x-show="modal" class="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center" x-cloak style="display:none"><div class="bg-white rounded-lg p-8 w-2/3" @click.away="modal=false"><h2 class="text-2xl font-bold mb-4" x-text="edit?'Edit Teacher':'Add Teacher'"></h2><form method="POST"><input type="hidden" name="action" :value="edit?'update':'create'"><input type="hidden" name="id" x-model="form.id"><div class="grid grid-cols-2 gap-4"><div><label class="block text-sm mb-1">First Name*</label><input type="text" name="first_name" x-model="form.first_name" class="w-full border rounded px-3 py-2" required></div><div><label class="block text-sm mb-1">Last Name*</label><input type="text" name="last_name" x-model="form.last_name" class="w-full border rounded px-3 py-2" required></div><div><label class="block text-sm mb-1">Phone</label><input type="text" name="phone" x-model="form.phone" class="w-full border rounded px-3 py-2"></div><div><label class="block text-sm mb-1">Email</label><input type="email" name="email" x-model="form.email" class="w-full border rounded px-3 py-2"></div><div><label class="block text-sm mb-1">Subjects</label><input type="text" name="subjects" x-model="form.subjects" class="w-full border rounded px-3 py-2"></div><div><label class="block text-sm mb-1">Salary Type</label><select name="salary_type" x-model="form.salary_type" class="w-full border rounded px-3 py-2"><option value="fixed">Fixed</option><option value="percentage">Percentage</option></select></div><div><label class="block text-sm mb-1">Salary Amount</label><input type="number" step="0.01" name="salary_amount" x-model="form.salary_amount" class="w-full border rounded px-3 py-2"></div><div x-show="edit"><label class="block text-sm mb-1">Status</label><select name="status" x-model="form.status" class="w-full border rounded px-3 py-2"><option value="active">Active</option><option value="inactive">Inactive</option></select></div></div><div class="flex justify-end space-x-3 mt-6"><button type="button" @click="modal=false" class="px-4 py-2 border rounded">Cancel</button><button type="submit" class="px-4 py-2 bg-blue-600 text-white rounded">Save</button></div></form></div></div></main></div></body></html>
